### ISSUE TITLE
Add prebuffering

### ISSUE THREAD

**Issue by Kefir100** [Kefir100/radio-ch1ller#1]
Client has to wait approx. 10 seconds before his buffer gets full and he can actually listen to the radio. Add 10 seconds of a buffer on a server that gets sent to the client immediately after new connection.

**Comment by daveyijzermans** [comment]
Hi! I'm using your code on my own website and there is a problem in Chrome where in the first 10 seconds or so of listening the music jumps, I think forward in time. I'm writing about it here because I think if might have to do with this feature. I first thought there might be something wrong with my application but I hear it on your website too (https://fridgefm.com/)
I'm also experiencing this on Safari, Firefox, Android and streaming in VLC, so I think this might be under your attention already. 😅

**Comment by Kefir100** [comment]
@daveyijzermans Hey mate, thanks for your feedback!

Yes, youre pretty right, the reason of such behaviour lies here 🙂 
This behaviour is somewhat intended (I didnt really ever considedered this as a big problem) and it is server-side - so it is agnostic of the browser youre using.
To be more specific the problem is the lack of synchronization between prebuffer and the actual stream. This is basically how the skip appears
1. The client connects and immediately gets the first 10 sec of prebuffer
2. The stream starts piping to the client.
3. When prebuffer drains on the client, the data starts coming from the buffer filled with stream <- the skip appears here.

You hear the skip due to the abrupt change of different moments of a track (i.e. different chunks at all). To fix such behaviour there should be some synchronization mechanism - so Ive created an issue https://github.com/Kefir100/fridgefm-radio-core/issues/160

Feel free to add comments and/or send a PR
